INSERT INTO interests (name) VALUES
('Baking'),
('Board Games'),
('Camping'),
('Cooking'),
('Dancing'),
('Drawing'),
('Fishing'),
('Gaming'),
('Hiking'),
('Knitting'),
('Music'),
('Painting'),
('Photography'),
('Reading'),
('Running'),
('Singing'),
('Swimming'),
('Traveling'),
('Basketball'),
('Football'),
('Soccer'),
('Tennis'),
('Volleyball'),
('Yoga'),
('Martial Arts'),
('Cycling'),
('Gardening'),
('Writing'),
('Skiing'),
('Snowboarding'),
('Video Editing');